version: '3.9'
services:
  db:
    image: postgres:15
    container_name: alpha_db
    ports:
      - "5436:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=alpha_db

  db2:
    image: postgres:15
    container_name: beta_db
    ports:
      - "5437:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=beta_db